name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v3
	  - name: Set up Python for Demo
	  uses: actions/setup-python@v4
	  - run: pip3 install pytest
	  - name: Run tests
	  run: pytest TP1/test.py
